name = "Adventures with Dad"
author = "John Bruett"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2c1119d00e1b970f29cad946615e30594a622d948ea5ee753cbf6842bb42b561"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.255"
